// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccoubtID int64 `json:"accoubt_id"`
	// Pode ser positivo ou negativo
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccoubtID int64 `json:"from_accoubt_id"`
	ToAccoubtID   int64 `json:"to_accoubt_id"`
	// Deve ser positivo
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
